### ISSUE TITLE
What would be the license for this project?

### ISSUE THREAD

**Issue by harshavardhana** [labbloom/bloom-tree#4]

**Comment by LumRamabaja** [comment]
We will remove the "patent pending" part from the papers to remove confusion. The patents serve only for defensive purposes. Every Bloom Lab data structure / algorithm / protocol will be an Apache Licence 2.0. We will add the appropriate licensing info to our repos during the upcoming days.

**Comment by harshavardhana** [comment]
Thanks @LumRamabaja

**Comment by klauspost** [comment]
@LumRamabaja Apache v2 sounds good, but it doesn't cover the patent. 

As far as I can tell (definitely not a lawyer) you can still hit users with patent license fees requests unless you grant explicit free use of any patent Bloom Lab may have in relation to the contents of this repo.

**Comment by LumRamabaja** [comment]
This is technically correct. We will make it explicit that people using our tech cannot be hit legally in any way. As a start-up we have these patents for defensive purposes only. We're in talks with lawyers to draft the correct language to reflect that.

**Comment by klauspost** [comment]
I deleted the comment since apache does indeed address patents, so I didn't want to spread false information. Thanks for clarifying!
